services:
  db:
    image: postgres:16.3-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    restart: always

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USR}:${POSTGRES_PWD}@db:5432/${POSTGRES_USR}
    depends_on:
      - db

volumes:
  data:
