services:
  db:
    image: postgres:16.3-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER:     ${POSTGRES_USR}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    restart: always

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  data:
