target-version = "py311"
line-length = 100

[lint]
select = ["ALL"]

ignore = [
    "D100", # undocumented-public-module
    "D203", # one-blank-line-before-class
    "D213", # multi-line-summary-second-line
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pylint]
max-args = 7
